[build]
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# URL redirects from old paths to new paths
[[redirects]]
  from = "/case-studies/:id"
  to = "/our-work/:id"
  status = 301

[[redirects]]
  from = "/case-studies"
  to = "/our-work"
  status = 301

# SPA fallback rule - serve index.html for all routes that don't match static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
