// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrizusckxltrbjsdlrla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyaXp1c2NreGx0cmJqc2RscmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mjk1MDQsImV4cCI6MjA3MTIwNTUwNH0.H2_oUN960_1sl26bWC0_F6FqWlX5W0JUPmr0sl71ZFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});